### ISSUE TITLE
ERROR:root:Unable to make new descriptors

### ISSUE THREAD

**Issue by alim11github** [bp-kelley/descriptastorus#11]
i did install descriptastorus via   pip install git+https://github.com/bp-kelley/descriptastorus   , and successfully installed  .but  every time when i import descriptastorus , i got this error (ERROR:root:Unable to make new descriptors, descriptor generator not installed,  but   Process finished with exit code 0  in pycharm)  . 

when i try this( from descriptastorus.descriptors import rdDescriptors, rdNormalizedDescriptors)  . i also got error (ValueError: RDKit2D: Failed to initialize: unable to find specified properties:
	fr_Al_COO
	fr_Al_OH
	fr_Al_OH_noTert
	fr_ArN
	fr_Ar_COO
	fr_Ar_N
)
i been stuck here few days  ,   i did try reinstall few  times   (f pip install git+https://github.com/bp-kelley/descriptastorus   or  github  source)   ,but it didn't  work.    (RDkit 2021.9.2    scikit-learn     already installed)
 
did i miss anything during deployment?   thank for any suggestion.

**Comment by bp-kelley** [comment]
It looks like these got moved in the rdkit.Chem.Fragments in rdkit 2021.9 and out of the main descriptorList, I'll patch the code to look for them there.

**Comment by bp-kelley** [comment]
Actually, I take it back, I'm unable to duplicate the issue:

```
>>> import rdkit
>>> rdkit.__version__
'2021.09.2'
>>> from  descriptastorus.descriptors import rdDescriptors
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
>>> rdDescriptors.RDKit2D()
<descriptastorus.descriptors.rdDescriptors.RDKit2D object at 0x103d45ee0>
```

Could you send the contents of rdkit.Chem.Descriptors.descList ?

**Comment by bp-kelley** [comment]
Are you using Conda or did you install rdkit via pip?

**Comment by bp-kelley** [comment]
```python -c 'import rdkit;print(rdkit.__version__);from rdkit.Chem import Descriptors;print(len(Descriptors.descList))'```

should be 208

**Comment by alim11github** [comment]
apologize！！ i been  little bit busy recent days, so i didnt reply to you.     
i uninstalled new version RDKit     and  pip install version 2021.03.5     and  it worked.
len of  desclist is 123 .
 
but i still got this error  :
2021.03.5
123
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW

However  ,Process finished with exit code 0, so i think this error  does not affect the result.
anyway, thanks for your help.

**Comment by bp-kelley** [comment]
It didn’t really work, you are missing quite a few descriptors when you pip install rdkit.

I suggest using anaconda/conda for rdkit as that is the only officially supported version.

----
Brian Kelley
