### ISSUE TITLE
The misspelt gilbrat distribution has been removed (use scipy.stats.gibrat)

### ISSUE THREAD

**Issue by c-w-feldmann** [bp-kelley/descriptastorus#20]
In the script [rdNormalizedDescriptors.py line #49](https://github.com/bp-kelley/descriptastorus/blob/master/descriptastorus/descriptors/rdNormalizedDescriptors.py#L49) distributions are loaded dynamically from scipy.stats.  

In scipy version 1.11.0 the [`gilbrat` function is replaced by the `gibrat` function](https://docs.scipy.org/doc/scipy/release/1.11.0-notes.html#expired-deprecations) (typo).   

This raises an error during initializing rdNormalizedDescriptors.py

Proposed fix:  
  - [x] Replace all values `gilbrat` with `gibrat` in [dists.py](https://github.com/bp-kelley/descriptastorus/blob/master/descriptastorus/descriptors/dists.py) 
  - [x] add ```scipy>=1.11.0``` in [requirements.txt](https://github.com/bp-kelley/descriptastorus/blob/master/requirements.txt)

**Comment by jan-janssen** [comment]
Solved in https://github.com/bp-kelley/descriptastorus/pull/21

**Comment by c-w-feldmann** [comment]
Thanks a lot!

**Comment by bp-kelley** [comment]
I still have to merge it :)

**Comment by bp-kelley** [comment]
The new version is up on pypi:
https://pypi.org/project/descriptastorus/2.6.1/
