### ISSUE TITLE
upgrade scipy version

### ISSUE THREAD

**Issue by zspishere** [bp-kelley/descriptastorus#24]
when packages installed as:
```
descriptastorus==2.6.1
scipy==1.8.1
```

will raise the error: 
```
python3.8/site-packages/descriptastorus/descriptors/rdNormalizedDescriptors.py, line 56, in <module>
    dist = getattr(st, dist)
AttributeError: module 'scipy.stats' has no attribute 'gibrat'
```

and, packages as below is ok.
```
descriptastorus==2.6.1
scipy==1.9.0
```

so, maybe `scipy>=1.9.0` is required? not `scipy>=1.7.0` in [requirements.txt](https://github.com/bp-kelley/descriptastorus/blob/master/requirements.txt).

**Comment by bp-kelley** [comment]
It should support both now, there was a bug in the gilbrat->gibrat check.
