### ISSUE TITLE
Errors met when installing rdkit in requirement.txt

### ISSUE THREAD

**Issue by zoey-shan** [bp-kelley/descriptastorus#30]
Thank you for sharing your amazing work.

While running the command `pip install git+https://github.com/bp-kelley/descriptastorus`, I met errors:
ERROR: Could not find a version that satisfies the requirement rdkit (from versions: none)
ERROR: No matching distribution found for rdkit
Such errors also rose when I ran the command `pip install rdkit>=2022.3.3` (following requirement.txt)
But rdkit>=2022.3.3 could be successfully installed when running `pip install rdkit_pypi>=2022.3.3`
Maybe requirements.txt needs to be modified

**Comment by bp-kelley** [comment]
rdkit_pypi isn't supported anymore, it was moved to just "rdkit", in fact this is noted in the rdkit-pypi repo:

https://pypi.org/project/rdkit-pypi/

```
NOTE: Older versions of RDKit might be available at the [rdkit-pypi](https://pypi.org/project/rdkit-pypi/) PyPI repository (pip install rdkit-pypi). rdkit-pypi is the old name of this project at PyPI. Future RDKit versions will be available at the rdkit PyPI repository. Please update your dependencies, i.e., change rdkit-pypi to rdkit.
```

What are you trying to install rdkit on?  Might it be an older version of OSX?
