### ISSUE TITLE
Metadata `does not match given version` Issues

### ISSUE THREAD

**Issue by Scienfitz** [bp-kelley/descriptastorus#37]
Hi,

in our CI pipeline we run a `pip-audit` step for a project. This is happening inside `tox-uv` environments where installation happens via `uv`.

We are getting an error `Caused by: Package metadata version '2.7.0' does not match given version '2.7.0.4'`
(see the pipeline [here](https://github.com/emdgroup/baybe/actions/runs/11238457616/job/31243295060#step:4:71))

Do you have any idea whether this is a problem in our setup or could be with the published version? Or even with an issue with `uv`?

`descriptastorus` is a secondary dependency we get due to `scikit-fingerprints`, for a temporary fix I pinned the package requirement to `descriptastorus==2.6.1` but ideally I would avoid such shenanigans

**Comment by bp-kelley** [comment]
I uploaded the "wheel" version not the source distribution as 2.7.0.5, inexplicable this one works while the source distribution does not.  I'll investigate.

I have yanked the 2.7.0.4 version

Note that the 2.6.1 version gave different feature results for rdkit 2024.03 this has been resolved.

**Comment by bp-kelley** [comment]
Please install the 2.7.0.5 release.

**Comment by bp-kelley** [comment]
I'll also say you should probably pin your release to < 3 as the 3.0 release will change the default results when new descriptors are added.

**Comment by Scienfitz** [comment]
fix confirmed, pin removed, ty
