### ISSUE TITLE
Typo (comma instead of a dot) breaks rdNormalizedDescriptors

### ISSUE THREAD

**Issue by beangoben** [bp-kelley/descriptastorus#39]
Should be `self.funcs` instead its `self,funcs`.
This error breaks some functionality, raising a `self` is missing.

https://github.com/bp-kelley/descriptastorus/blob/d0cd71dc9ff2aee961783b883be0cc9c9399646d/descriptastorus/descriptors/rdNormalizedDescriptors.py#L114

**Comment by bp-kelley** [comment]
Thanks for this, it looks like these got accidentally merged from a bad branch.  The correct code is in the v/3.0.0 branch, I'll go ahead and merge the correct version.
