### ISSUE TITLE
Warnings upon import

### ISSUE THREAD

**Issue by hesther** [bp-kelley/descriptastorus#7]
Dear descriptastorus team, 
Our software project [Chemprop](https://github.com/chemprop/chemprop) relies on descriptastorus (thanks for this great project btw) to compute a couple of descriptors for molecules. Newly installed versions of descriptastorus cause a couple of warnings when imported:
```
>>> import descriptastorus
WARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
```
The descriptors seem to be unaffected by the warnings, however, they are always a cause of concern to our users. What causes the warning, and is there anything we can do about it? The warnings occur over different OSs and python versions (I can create a list if that is of any help). Thanks for your help!

**Comment by bp-kelley** [comment]
These warning are simply indicating that we don't have distributions for these new RDKit descriptors.  I prefer to keep them in so know when rdkit gets updated.  What I can do is move these to a descriptastorus namespace so you can turn off warnings.

In any case, the bcut descriptors are being tested now.

**Comment by hesther** [comment]
I see - moving them to a descriptastorus namespace sounds very good to me (if you have the time to do so), otherwise we can simply wait on the cut descriptors being implemented, too! Thank you!

**Comment by kevingreenman** [comment]
Is there any update on plans to move these to a descriptastorus namespace or on the new descriptors being implemented?

**Comment by bp-kelley** [comment]
I forgot to close this issue earlier, but the logging is all done in a descriptastorus namespace now.  You can find the latest version on pypi (2.6.1)

```
pip install descriptastorus>=2.6.1
```

**Comment by bp-kelley** [comment]
Also, you shouldn't see the warnings anymore.

**Comment by hesther** [comment]
Great, thank you!
